In [14]:
import torch
x = torch.empty(2,3) # avector of dimention 2x3
print(x)


tensor([[-1.6027e+35,  4.3091e-41, -4.8665e+13],
        [ 4.3093e-41, -4.1046e+13,  4.3093e-41]])


* we can also use `torch.zeros()` or `torch.ones`
* we can use random tensor as `torch.rand(3)`
* we can use random tensor with all negative elements as `torch.randn(3)`.
* wecan give datatype using `torch.ones(2,2,dtype=torch.float16)`.
* we can infer the size from `x.size()` or `x.shape`

In [17]:
x.size()

torch.Size([2, 3])

In [15]:
z = torch.tensor([2.5,0.1])
print(z)
print(z.shape)

tensor([2.5000, 0.1000])
torch.Size([2])


In [16]:
#random tensor
torch.rand(2,2) #dim = 2x2

tensor([[0.8243, 0.8788],
        [0.5786, 0.7714]])

In [8]:
x = torch.tensor([[2,3],
                  [4,5]])
y = torch.tensor([[2,2],
                  [9,8]])
print(x)
print()
print(y)

tensor([[2, 3],
        [4, 5]])

tensor([[2, 2],
        [9, 8]])


### addition

In [ ]:
#addition
x+y
torch.add(x,y)
x.add_(y) # it changes x to x+y


tensor([[ 4,  5],
        [13, 13]])

In [ ]:
x

tensor([[ 4,  5],
        [13, 13]])

similarly we can do subtraction

### multiplication

In [ ]:
x = torch.tensor([[2,3],
                  [4,5]])
y = torch.tensor([[2,2],
                  [9,8]])

torch.mul(x,y) #this is doing element wise multiplication and not matrix multiplication

tensor([[ 4,  6],
        [36, 40]])

similarly we can do division as well

### slicing

In [ ]:
x = torch.tensor([[2,3,4,7,4],
                  [4,5,2,3,6],
                  [8,9,1,6,2],
                  [8,9,1,6,2]])
x[:,0] # first element of each row packed into a tensor and returned

tensor([2, 4, 8, 8])

In [ ]:
x[0:2,:]

tensor([[2, 3, 4, 7, 4],
        [4, 5, 2, 3, 6]])

In [ ]:
x[0:2,:2]

tensor([[2, 3],
        [4, 5]])

if only one value is present we can convert it into scalar using `.item()`

In [ ]:
x[1,2].item()

2

### shape changing of tensor or vector

In [ ]:
x.shape

torch.Size([4, 5])

In [ ]:
x.view(20)

tensor([2, 3, 4, 7, 4, 4, 5, 2, 3, 6, 8, 9, 1, 6, 2, 8, 9, 1, 6, 2])

In [ ]:
x.view(2,4) # this gives error as 2x4 is not 15

RuntimeError: shape '[2, 4]' is invalid for input of size 20

In [ ]:
x.view(2,10)

tensor([[2, 3, 4, 7, 4, 4, 5, 2, 3, 6],
        [8, 9, 1, 6, 2, 8, 9, 1, 6, 2]])

-1 automatically assigns the row or column missing but atleast one dimension should be given

In [ ]:
x.view(4,-1)

tensor([[2, 3, 4, 7, 4],
        [4, 5, 2, 3, 6],
        [8, 9, 1, 6, 2],
        [8, 9, 1, 6, 2]])

we can convert a tensor to numpy vector using `x.numpy()`

In [ ]:
y = x.numpy()

In [ ]:
import numpy as np

we can convert numpy to tensor using `torch.from_numpy(y,dtype=int64)`

we can transfer operations of tensor from CPU to GPU(if cuda drivers are available) as follows:
```python
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.tensor([[2,3,4,7,4],
                  [4,5,2,3,6],
                  [8,9,1,6,2],
                  [8,9,1,6,2]],device=device)
    # we can also use x.to(device)
    # after this we cannnot simply use x.numpy() as numpy cannot use GPU thus we follow this
    x = x.to("cpu")
    x.numpy()
```

if we want to compute grandient for a tensor we can do that using
```python
torch.tensor(<matrix>,requires_grad=True)
```